[package]
name = "japanese-immersion-cli"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "ji-cli"
path = "src/main.rs"

[dependencies]
serde_json = "1.0.150"
serde = { version = "1.0.228", features = ["derive"] }
reqwest = "0.13.4"
tokio = {version = "1.52.3", features = ["macros", "rt-multi-thread"]}
rusqlite = { version = "0.40.1", features = ["bundled"] }
clap = { version = "4.6.1", features = ["derive"] }
chrono = "0.4.45"
clap_complete = "4.6.7"
csv = "1.4.0"
dirs = "6.0.0"
colored = "3.1.1"

